### PR TITLE
update dependencies and tests (WIP)

### PR DESCRIPTION
**Pull request by chicoxyzzy**
WIP here is because I can't figure out what should I use instead of `tap.createConsumer` which is missing in node-tap >= 1.0.0. @isaacs is there any alternatives of `createConsumer` method in node-tap 2.2.x?

These tests should be fixed to work with tap 2.1.1
- [ ] array
- [ ] end-as-callback
- [ ] exit
- [ ] fail
- [ ] nested-sync-noplan-noend
- [ ] nested
- [x] only
- [x] timeoutAfter
- [x] too_many

### CODE REVIEW

**Comment by ljharb** [comment]
Why do `concat-stream` and `falafel` need updates?

**Comment by isaacs** [comment]
node-tap just uses `tap-parser` to parse streams, it doesn't have a separate "consumer" concept any more.

**Comment by chicoxyzzy** [comment]
@ljharb actually I'm trying to update tap to 2.1.1 as well but I am still tying to figure out what should I do to update tests for:
- array
- end-as-callback
- exit
- fail
- nested-sync-noplan-noend
- nested
- only
- timeoutAfter
- too_many

**Comment by chicoxyzzy** [comment]
I don't work on this for almost a year so I'll better close it

**Comment by ljharb** [comment]
Thanks - this was done by #318 recently anyways.

**Pull request closed without merging**
