### PR TITLE
[Tests] add test case for #519 for test.comment() in createStream/objectMode context

### LINKED ISSUE #519: tape@5 breaks test.comment() in createStream/objectMode context
```bash
pi@chat:~/tape-bug $ node --version
v14.2.0
pi@chat:~/tape-bug $ ls
repro.js
pi@chat:~/tape-bug $ cat repro.js 
var tape = require("tape");

tape.createStream({ objectMode: true }).on("data", (row) => {
  console.log(JSON.stringify(row))
});

tape("test.comment", (test) => {
  test.comment("message");
  test.end();
});
pi@chat:~/tape-bug $ npm i tape@4
+ tape@4.13.2
pi@chat:~/tape-bug $ node repro.js 
{"type":"test","name":"test.comment","id":0,"skip":false,"todo":false}
"message"
{"type":"end","test":0}
pi@chat:~/tape-bug $ npm i tape@5
+ tape@5.0.0
pi@chat:~/tape-bug $ node repro.js 
{"type":"test","name":"test.comment","id":0,"skip":false,"todo":false}
/home/pi/tape-bug/node_modules/tape/lib/results.js:63
                res.test = id;
                         ^

TypeError: Cannot create property 'test' on string 'message'
    at Test.<anonymous> (/home/pi/tape-bug/node_modules/tape/lib/results.js:63:26)
    at Test.emit (events.js:327:22)
    at Test.bound [as emit] (/home/pi/tape-bug/node_modules/tape/lib/test.js:84:32)
    at /home/pi/tape-bug/node_modules/tape/lib/test.js:149:14
    at forEachArray (/home/pi/tape-bug/node_modules/for-each/index.js:12:17)
    at forEach (/home/pi/tape-bug/node_modules/for-each/index.js:54:9)
    at Test.comment (/home/pi/tape-bug/node_modules/tape/lib/test.js:148:5)
    at Test.bound [as comment] (/home/pi/tape-bug/node_modules/tape/lib/test.js:84:32)
    at Test.<anonymous> (/home/pi/tape-bug/repro.js:8:8)
    at Test.bound [as _cb] (/home/pi/tape-bug/node_modules/tape/lib/test.js:84:32)
pi@chat:~/tape-bug $ 
```

This functionality is broken by https://github.com/substack/tape/commit/11b7d850ffaa8cb679419ff4a0e314b06a3225b9 which adds `'use strict';` to the top of `/lib/results.js`.

It looks like a longer-standing issue, though. It seems to me that `emit('result', res)` is  meant to pass a result-like object, whereas `Test.prototype.comment` has treated the comment string as the result object ever since being added in https://github.com/substack/tape/commit/7948e2ee439135efee86ea0b7ce24c9deea4b018.

### PR DESCRIPTION
**Pull request by DavidAnson**

### CODE REVIEW

**Comment by ljharb** [comment]
oops! this wasn't linked to #519, so i committed fb94836 before realizing this was here.

**Comment by DavidAnson** [comment]
OK, thanks! Out of curiosity, how should I have linked it to the issue?

**Comment by ljharb** [comment]
Just referencing it with `#` and the number, like I did in my comment, would be sufficient :-) You can also comment on the issue with a similar reference to the PR number.

**Comment by DavidAnson** [comment]
I put “fixes ###” in the commit message and it did show up in the issue timeline. No worries here, just wanted to be sure I was doing things right.

**Comment by ljharb** [comment]
ah, you're right! however, a commit reference in the timeline is unfortunately a lot more subtle than a PR reference, so i missed it :-/

**Comment by DavidAnson** [comment]
Got it. I’ll be more explicit in the future!

**Pull request merged**
