### PR TITLE
Comments should not make exit code incorrect. Fixes #92

### LINKED ISSUE #92: t.comment() = fail exit code
Is this correct behaviour?

Including any test comments seems to fail a suite.

```js
// test.js
var test = require('tape')

test('comment test', function(t) {
  t.comment('this is a comment')
  t.ok(true)
  t.end()
})
```

```
> tape test.js
TAP version 13
# comment test
# this is a comment
ok 1 (unnamed assert)

1..1
# tests 1
# pass  1

# ok


> echo $?
1
```

### PR DESCRIPTION
**Pull request by grit96**
PR #94 wasn't merged in, so creating a new PR

### CODE REVIEW

**Comment by ljharb** [comment]
`v2.13.4` does have that commit merged in, in 17894caf61fbaa908bfc625a1119c16ab316afb6 (note it's parent), but you're right that this never made it into v3.0 or v4.0.

After this gets merged in, it should probably also be backported on top of v3.0.3, v3.1.0, v3.2.0, v3.3.0, v3.4.0, v3.5.1, and v3.6.0 - and all of them bumped with a patch release, before publishing this change as v4.0.2. @substack/@raynos, sound ok?

**Comment by ljharb** [comment]
@grit96 can you also rebase this on top of master such that there's no merge commit, just the single commit you're cherry-picking in?

**Comment by grit96** [comment]
@ljharb done

**Comment by Raynos** [comment]
back porting is amount of effort.

Let's get it into master and cut a new patch.

**Comment by Raynos** [comment]
Published 4.0.2

**Pull request merged**
