### PR TITLE
Travis: Add Node v4

### PR DESCRIPTION
**Pull request by wbinnssmith**
I imagine the entry "4" will continue to be the latest stable release of the 4.x line on travis.

### CODE REVIEW

**Comment by ljharb** [comment]
I don't see any reason to remove `iojs` if it continues to pass. Also, instead of `4`, you can use `node` to test the latest version of node.

**Comment by wbinnssmith** [comment]
Hm. When node hits 5 (which it will in the coming months iirc), "node" will simply move onto 5 (unless travis decides to keep node pointing to the latest LTS instead of the latest node) and 4 will become untested. Either way, I imagine it will be best to be explicit. [See browserify's patch](https://github.com/substack/node-browserify/commit/97a122e9c885158733e0fa2f4eecf5d238202381).

**Comment by ljharb** [comment]
¯\_(ツ)_/¯ not sure what node LTS has to do with an arbitrary library's chosen support level.

I don't mind putting `4` in here - not `4.0.0`, though - but I still think it's useful to keep `iojs`.

**Comment by wavded** [comment]
I second that its still useful to keep `iojs`.

**Comment by wbinnssmith** [comment]
All right, the patch simply adds "4" now.

**Comment by ljharb** [comment]
LGTM

**Pull request merged**
