### PR TITLE
Add link to tape-player (in-process reporter) to readme.

### PR DESCRIPTION
**Pull request by DavidAnson**

### CODE REVIEW

**Comment by DavidAnson** [comment]
If you do not approve of this approach, I will not be offended. Just reject the PR.

**Comment by ljharb** [comment]
Seems like it might be easier to make a test runner (a binary) instead of a side-effecting require.

**Comment by DavidAnson** [comment]
I dunno, this was pretty easy. :)

But seriously, I’m not sure I understand the suggestion. If you don’t mind explaining the proposal a bit more, I’d appreciate it. I’m happy to use `tape`, I just didn’t want to pipe to a formatter.

**Comment by ljharb** [comment]
That's what I mean - make a new runner, so instead of `tape foo`, which they'd expect to pipe to a TAP formatter, `tape-player foo`, which just prints it out formatted.

**Comment by DavidAnson** [comment]
I get it, thanks, but it seems weirder to me than this and maybe trickier? With how I’ve done it, the use of `tape` is clear in the script command and the behavior of the exit code obvious. Again, no hard feelings if you reject this PR. This works for me, but I may be the only one who likes it.

**Comment by ljharb** [comment]
I think it's fine, but let's move it under "other" instead. It's not a formatter, because it's not configurable or swappable - it's just something that patches tape to print "not TAP".

**Pull request merged**
