### PR TITLE
Added --save-dev to install instruction

### PR DESCRIPTION
**Pull request by mathiasrw**
My 2 cents...

### CODE REVIEW

**Comment by troutowicz** [comment]
Not everyone that installs tape plans on developing tape.

**Comment by substack** [comment]
@troutowicz: this would install tape as a devDependency, not a dependency in package.json. I think that is what most people will want.

**Comment by ljharb** [comment]
Although I personally don't use the save options on `npm install`, since it messes with my package.json formatting, I think including them as a default is the appropriate thing to do for the majority of users. This LGTM.

**Comment by mathiasrw** [comment]
:+1:

**Comment by wavded** [comment]
:+1:

**Comment by troutowicz** [comment]
> this would install tape as a devDependency

Oops... :sob:

**Pull request merged**
