### PR TITLE
[readme] improve `t.throws`/`t.doesNotThrow` documentation

### PR DESCRIPTION
**Pull request by cagross**
Hi Jordan,

Sorry for the delay on this.  Per our discussion (in issue #540), in this commit I have edited the README to describe the following:

* The behavior of `t.throws()` when the `expected` parameter is a string.
* The fact that the `expected` parameter for `t.throws()` can be a validation object (just like Node's `assert.throws()`).

Have a look and let me know if anything is incomplete or inaccurate.

For now, due to time constraints, I omitted an example of validation object usage, and simply added a link to the Node documentation.  I'd very much like to add such an example (as they've done on [the Node documentation page](https://nodejs.org/api/assert.html#assert_assert_throws_fn_error_message)), but I'm out of time today, and might get busy with work tomorrow for the next week or so.  I can try to keep you posted here on that schedule. But it may be the case where you want to merge these edits now, and I open a new pull request next week which adds the validation object example.

Two more questions that we might want to address now (or earmark for future discussion):

1.  Are there files other than the README that should be updated with this information?  If so, I can do that if you want (either in this pull request or a separate pull request in the future).

2.  In the README, should other methods be updated with similar information?  i.e. are there other methods with an `expected` parameter that cannot be a string?  If so, I can do that if you want (either in this pull request or a separate pull request in the future).

--Carl

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Thanks, this looks great! Mind making the same changes to `doesNotThrow`, just below?

**Comment by cagross** [comment]
> Mind making the same changes to doesNotThrow, just below?

OK sure.  Give me 24 hours and I'll push a new commit to this PR.

> (There aren't any other files to update; and other than throws/doesNotThrow, let's save additional updates for another PR)

OK noted on all.

**Comment by cagross** [comment]
OK I just pushed a second commit with the edits to `t.doesNotThrow()`.  I omitted the validation object as an allowed value for `expected`, since Node's doesNotThrow does not allow it as a parameter.  I hope that was correct.  If not let me know and I can add it back in.

I also added some of the existing verbiage from `t.doesNotThrow()` to `t.throws()` because it looked helpful (speciifclaly the regex usage example).  Let me know if I did so incorrectly.

**Comment by cagross** [comment]
Great!  Give me a few more days and I'll add that validation object example we discussed.  

If new issues are submitted related to thisarea, feel free to tag me (or this PR, or my commits, or whatever), and I can take a look.

**Pull request merged**
