### PR TITLE
Fix Windows path support in error messages

### LINKED ISSUE #220: No line number provided in Windows on failed tests (and proposed fix)
Hi,

When I'm using windows with nodejs, tape does not provide an at: field with the line numbers if a test fails. 

It is fixed by placing:
```
var windowsPath = dir.substr(1,1) === ":"; // check for windows path if the second letter is a :
if (windowsPath)
  dir = dir.replace(/(\\)/g,"/").substr(2);  // swap \ for / and remove the D: or C: from C:\
```
at https://github.com/substack/tape/blob/master/lib/test.js#L212

and inserting:
```
if (windowsPath) 
  err[i] = err[i].replace(/(\\)/g,"/");  // swap \ for / 
```
before https://github.com/substack/tape/blob/master/lib/test.js#L214

This bug is caused by the drive letter before the path which you do not seem to expect in the rest of the logic and the inverted slashes.

I can do a pull if you'd like?

Regards

### PR DESCRIPTION
**Pull request by hgwood**
Supersede #221. Fix #220. Generally makes tape support more kinds of stacktrace formats.

### CODE REVIEW

**Comment by hgwood** [comment]
The stacktrace that is now picked up in some tests is internal to Node and dependent on the version of Node, so the tests break on everything but Node 6. I'm going to tweak the regex to exclude this case.

**Comment by hgwood** [comment]
If fixed by excluding stacktrace elements where the location is only a filename. It must contain at least one path separator.

**Comment by ljharb** [comment]
I think this change will need extensive tests to prevent against current and future breakage.

**Comment by hgwood** [comment]
What test cases would you like to see?

**Comment by ljharb** [comment]
Things that verify important aspects of current stack traces to ensure that a regex-based approach (which is hard to get right) isn't breaking anything. These tests may already exist, of course, but I suspect they don't.

**Comment by hgwood** [comment]
Right. So right in fact, the regexp I'm using here may only work in Node envs. I was focused on that, but tape is supposed to work in browsers too right? [Here](https://github.com/errwischt/stacktrace-parser/blob/master/lib/stacktrace-parser.js#L13) we can different regexp for different envs.

What about using https://www.npmjs.com/package/stacktrace-parser?

Alternatively, one quick and dirty fix I tested for Windows is to use `path.sep` [here](https://github.com/substack/tape/pull/295/files#diff-dd2e881af3311f834199c7b515cff0c7R226) and replace `\/` by `(?:\/|[A-Z]:\\` [here](https://github.com/substack/tape/pull/295/files#diff-dd2e881af3311f834199c7b515cff0c7L229) (and in the 2 other occurrences in the next lines). I did not take that route in the end because it just adds a special case instead of being general. For example, Windows network paths would not work with this. However, I would settle for it if you would be more comfortable with it.

**Comment by ljharb** [comment]
@hgwood Given #316, should this PR be closed, or rebased and re-evaluated?

**Comment by hgwood** [comment]
I will close it as I'm personally satisfied with #316. Anyone willing to go the extra mile to support special paths (like @bsuh) can always open a new PR.

**Pull request closed without merging**
