### PR TITLE
Loop over all files after resolving glob patterns

### PR DESCRIPTION
**Pull request by kl0tl**
Closes https://github.com/substack/tape/issues/223.

### CODE REVIEW

**Comment by Kl0tl** [comment]
That’s weird, [test/require.js](https://github.com/substack/tape/blob/master/test/require.js) is failing on node 0.10. It works with `t.plan(1)` instead of `t.end()` in [test/require/a.js](https://github.com/substack/tape/blob/master/test/require/a.js) though, but I’m not really sure why. Would it be enough to fix the failing test @ljharb ?

**Comment by ljharb** [comment]
I think we should assume the test is correct.

**Comment by ljharb** [comment]
Could you add a test that fails *without* your change?

**Comment by kgryte** [comment]
@Kl0tl Any updates on this?

**Comment by jcama** [comment]
Hi! @Kl0tl I'm working on a similiar test framework project. Wont to help me out? If so drop an email at jonnycasamillo@gmail.com. For others as well. Feel free to send an email!

**Comment by r0mflip** [comment]
Seemed to be fixed by https://github.com/substack/tape/pull/374

**Pull request closed without merging**
