### PR TITLE
Add support for before and after hook

### PR DESCRIPTION
**Pull request by amrish7**

### CODE REVIEW

**Comment by ljharb** [comment]
Rather than creating a fork, have you attempted to PR any of these features into tape itself?

**Comment by amrish7** [comment]
Hi @ljharb The Fork is temporary... I just want to add more features to my fork and do a one shot PR with these features. Moreover, I wasn't sure if the community was open to `before` and `after` hooks on Tape

**Comment by gabrielcsapo** [comment]
the difference between mocha and tape is the non existence of life cycle hooks that causes unit tests to not be pure, isn't that a fundamental philosophy of tape? It is the reason I use it for all of my projects open source or work related.

**Comment by snuggs** [comment]
Well.. @gabrielcsapo doesn't necessarily mean "non pure" just means have to take care of ifecycle within each respective test example. I just use a `before` and a `after` helper that can take parameters perhaps a callback. Just a thought. There's ways to make "pure" just the developer ergonomics aren't there. That said, lifecycle hooks would be nice.

**Comment by gabrielcsapo** [comment]
@snuggs I am just reiterating some design principles that were discussed to differentiate mocha 

- https://github.com/substack/tape/issues/59
- https://github.com/tapjs/node-tap/issues/138

Even @substack said;

```
I vote for no. The economy of using test() for serial execution blocks is very simple and nice. I think a section in the docs about how to beforeEach/afterEach using test() would be just as good without adding more redundant clutter to the API.
```

**Comment by amrish7** [comment]
I do see benefits from lifecycle hooks especially around pulling boiler plate code (like cleaning up spies/mocks) into these hooks thereby making test cases less noisy. 

That being said, I don't want to push my philosophy on these lifecycle hooks onto the community! I could live with a forked version! May be these features gets pulled in at a later stage or it lives outside in a fork for eternity 😄

**Comment by gabrielcsapo** [comment]
@amrish7 I think as a plugin it would make sense, I like the idea for some use cases, but as a base it makes sense from the statements by substack to keep the runner as serial as possible.

**Comment by snuggs** [comment]
@amrish7 this is AWESOME! I let about 5,000 of my closest friends know. We <3 tape!

capture d ecran 2017-07-28 a 11 24 10

**Pull request closed without merging**
